### ISSUE TITLE
Please Enable IOS support.

### ISSUE THREAD

**Issue by kadarsh11** [Pikaju/FlutterBraintree#1]

**Comment by gmaxferr** [comment]
Do you have the iOS implementation planned for the time being?
When is it expected to be implemented (if ever)?

Thanks

**Comment by Pikaju** [comment]
I sadly do not have the hardware to develop for iOS. Any pull requests are greatly appreciated. I will try to get my hands on a Mac soon but I don't know when that will be.

**Comment by ericel** [comment]
@Pikaju I would love to collaborate and we can come out with support for IOS. I do own a mac but new to flutter, would need a lot of guidance for IOS implementation. How can we work this out if u are willing to help with the process..seems u are fluent with Flutter.

**Comment by ersjoh** [comment]
I've just open a PR for [supporting iOS](https://github.com/Pikaju/FlutterBraintree/pulls).
