### ISSUE TITLE
Problem with pod install

### ISSUE THREAD

**Issue by fipooo** [Pikaju/FlutterBraintree#17]
When I try tun run pod install this error show up.

"[!] CocoaPods could not find compatible versions for pod "flutter_braintree":
  In Podfile:
    flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)

Specs satisfying the `flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)` dependency were found, but they required a higher minimum deployment target."

How to fix it?

**Comment by Pikaju** [comment]
Hi, did you uncomment the line at the top of your `ios/Podfile`?
Something along the lines of
```ruby
platform :ios, '10.0'
```
might help.
