### ISSUE TITLE
MissingPlugException --iOS requestPaypalNonce

### ISSUE THREAD

**Issue by luakt1955** [Pikaju/FlutterBraintree#29]
Under IOS, when PayPal Vault Flow and PayPal Checkout Flow are clicked, missing plugin exception occurs. The Android has no problem.

**Comment by Pikaju** [comment]
The newest version `1.0.0` should support custom UI for iOS, could you try and see if it works?

**Comment by Pikaju** [comment]
I'll assume this is fixed now, please open a new issue if necessary.
