### ISSUE TITLE
Google pay without totalPrice

### ISSUE THREAD

**Issue by SeriousMonk** [Pikaju/FlutterBraintree#90]
I should be able to include Google Pay as payment method in the BraintreeDropInRequest without specifying a currency or an amount.
In my case I need to create a subscribtion. Braintree docs say that I must first create a Customer with a payment method in the Vault and only then I can create a subscription.
I am therefore using the DropIn UI just to get a payment method for the customer. So you see how I can't specify a price since it is defined in the Braintree dashboard. It would be very bad practice to hardcode the price in the client...

**Comment by libaipeng1314** [comment]
Has your problem been solved? My problem is not Google payment

**Comment by pikaju** [comment]
I think Braintree does not support subscriptions with Google Pay. Only one-time instant purchases.
