### ISSUE TITLE
PlatformException(error, Merchant account not found, null, null)

### ISSUE THREAD

**Issue by lohitbura** [Pikaju/FlutterBraintree#94]
Getting this error ..
Here is my Implementation
Please Help  

final request = BraintreePayPalRequest(
              amount: amount.toString(), currencyCode: store.currencyCode
          );

 final result = await Braintree.requestPaypalNonce(
              responseTokenData["value"]["token"],
              request,
            );

**Comment by TheOneWithTheBraid** [comment]
How did you solve this?
